language: node_js
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile && cd functions && yarn --frozen-lockfile --ignore-engines && cd ..
cache: yarn
script:
  - yarn test && yarn build
deploy:
  provider: firebase
  project: default
  edge: true
  token:
    secure: FAtQhBazdZ4SWLiT4+zArha9YMUgEKEviRNdyyUFkMA8kVpPTL81IzcqI+zr0mzJWRCL9XSsJBRRSgAbws3wJ1Eg5ewp0YJoOFMtDgrw/z0aNN9aFdYvUOa8Zv4de2qh3LBmorg0QgDyYQeC2GVKmZKifoM6TeXvsU85eX6Fp1+OWY3dS2KvYk92TXcy5w9S36J0WgBWSg2OxGhSpQx+UOiWn7il5OQh3UOKYUTNmJJ9xOjBQHEYrQNa99uMx8cRVx8OyGA2eaM54EMB0ZiDvfOGr3iho3ilrI631RFF3N9ECqAohZOUPzIm32PZHWIBpfb6xrYxrysNvu1bxEsuJTwv9jfs/x952ji2KBlFSwA9nW+ndDe7XrCpSNLamruII6/kZ0nmPNzjVE/GMgHmEPkfuRgP8t1NHOqKYJv/a6Uu7MKLEpNaHXtycxXWTAFitqbnqFWGXmD0E17c1gJ9yt3IQ+abK/uGr1UQufrcYIO0nqJ6yZZzV2DyGlb38EmfMsPGjdpBEF20piNejhQmQUOp114CW8YgRoTHRBPoHvTfSz6SlJyYQXNQ2IW6YBfYcWQN/GpuJ4NLsrgHSdr62IwZopdtPZ9lMpssV8ewsN+i/+zphvFbxtjojs+Dp3nJ6+nCzvddn4NJhAh+UQQySeSzbFAKjVaEUTWhmRdsf7k=
