language: node_js
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile && cd functions && yarn --frozen-lockfile --ignore-engines && cd ..
cache: yarn
script:
  - yarn test && yarn build
deploy:
  provider: firebase
  project: default
  edge: true
  token:
    secure: FT5XLUu6HPI4j1LVWAMNifgh/jUIKt9jkavAQ/9s5lqEC0yCWYbgc3WhK2APiMgvp8Fi1ePQDGTkAdYXMQisuCW7ezgAZDzAwnIKNXFRhdqojA2EwRpVfFNlShyM5AHuPgMX/E3xjEtDf418GcleyYCECmPcW0NzN+YBTtNF0yjWRI9qlZqKADiC8T5fFKfPVnX88Z1alsiFGD5176r9Wx6tr17+H4YHsZ8zUnXWPHP0OngoJzRpdDlb6qhqB+DKNP/MyD2JSEFUkZtysXKnw7VJR8VXmrCA3Vgmcuy4Sp+zdHRpoKLltKJQlT6za2wDAi6MNpoEAsLulhFBWDHwat9ysTZLVk2QOYiOOH4gWoNxrLZsMRcMyKSGBpAWFUPkpjhh6XWu3OEEEd9mMDqgumIh6DyrYA+9QVf6lVboVn7wmVLl8G77G2vHQUlhJVW+jcQ4JxLP5dQh83/d/HkQGd5sAiGLbrmtNIM+CL0Jx1A8RyuUM1e578gsjwC95WG/F27rBeoSy92HVnLSt4+C0xJ1vwsxaOAhz0ERhzWu4Stha1m7/+Zg4p5+HdNIgGFkjaVl6XSoAIQUOVexDFvE/kZgidXcPfrY9c9TvYbswQo0Pjw1tz2BUfPtn1hrAD1nIP7otdzM7xwdzFO6ec68plryGi76Sy/WqoGiWtFj4fI=
