language: node_js
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile && cd functions && yarn --frozen-lockfile --ignore-engines && cd ..
cache: yarn
script:
  - yarn test && yarn build
deploy:
  provider: firebase
  project: default
  edge: true
  token:
    secure: Y3ufmoTBozs7SkZ6JuB+j18vKtMVhrtFpkC3VB5MHc/JxP9sDbpfHxmLHNvTzCnROc0e3wdH8xNbJE3VBjp6jp0uhXAQxQogzThMtaTD9NTJrg1EeXjzxPsveV+9scO4UGemlbl2Eh3C0EDJxfePv1CJZfEfc6DYupXeIIiz+yqIsuREmNvRX7lPWe7YUJZMivdJnD+Re8ZwbbQbTfDQdHlcF1o5IOWNuwrugOsqD8YcA6IKEqpeaDGpCVKZaO/nnxWCaN15GeXcDwOETy+UmiwiaeenkGVUxlATPaLxFDiAVNfDnhsw+sQPEq4LqnqxI5Nv4rNSI0k4z1cwLUNuLn6xDGZfWjzToVHGnszSqE+KhKLk2CCmJ+GxERYrYercL0d4wqOIgR4jXONEHgEo1ifjII/Y3QslUagMyKWHwd7WyXR9oKvK4dIunQm4gfCMtZet9fZrYYcwQzkWF1052IAbw8OFfpThH6zj5txqT+FKJNqlCsLN4nI606WRZYzPude//f63oOAjuabFBuok3G1jdC4U36CJ9j0zHd+odb70Z+9fb/CJaUilqrpwjblTKfyP61NGFZJbdrdyLq0eUOarfmxoYY+4SHivNiPCFtvJS5K3Xi7P1zJ9Zjqo+nBZp0Vj2aXxjdBYuPT/3YZj6nDlHH+ypHKqRpu6KU8mZVc=
