language: node_js
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile && cd functions && yarn --frozen-lockfile --ignore-engines && cd ..
cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.config/yarn/global
script:
  - yarn test && yarn build
after_success:
  - yarn global add firebase-tools && firebase use default && firebase deploy
