language: node_js
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile && cd functions && yarn --frozen-lockfile --ignore-engines && cd ..
cache: yarn
script:
  - yarn test && yarn build
deploy:
  provider: firebase
  project: default
  edge: true
  token:
    secure: mJEZvHxhcOalNNx7d45zHx1tFWqAlfMruuU6QK3fHgLungR1098DQvachLVb33cHJsyd76NOHFC6aBD5d1aJ0g3DO4agvXNP7KrNOoZ2UvFr3NlJIKm58cwPNIYBvKBEikqHyQMQKEwiwE7bVwCmlt954fncfRbW6zty1G9dx5ZcZCbIyKxjGbMJ48401pAuoEXwwFGKzqDu7y0/JztLFQcHH3JYGmsShT/n5du7jCTm/vCPHWLemOBUNUmVNrranyv1KlnEQv05sVONPoNomwv3ehuo64iMG6sBoz/ORkNbWqbC5jeA+9PYPFJO3EK5ePWbL/M4MXLdrDMVoPFTDgPZzjpHF/YtDnuJT7GWFXZrZ2NXKIKEGtNQDre2lB8S42t/Jvu0icYYjt76cnyjB1uXVonHfZENOYgpLOkLGuijhvy771sR3P36pJCNHSQikfKnRARO6URMU/4oPwE/yHi/xbB5ZiiB/u8x7SSMucx3WFrK5hlacJ7zdqNRanqKRsG8j3XPtfRDIJ8zxCMZtHwCzh8WD3uQW6/x1BXUUEJB5FkoCT8Cl8FGYnBQsxxaVWH6qYZpH+u0n2zuMjWmtjEIIzeZKclgAWgbqFZ/npwByxw6QdDJKIyweqs6UcdHyIi90Pl55CfFfB+R6yXQZciGS/pN+TADq204F4b7bHc=
